server:
  port: 8086

api:
  domain: jsonplaceholder.typicode.com
  endpoint:
    user: /users

spring:
  datasource:
    # Postgres
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bc2405p_db"
    username: postgres
    password: Admin1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop 
